"""Initial migration

Revision ID: d8ac1f205a66
Revises: 
Create Date: 2024-06-19 15:31:18.339876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ac1f205a66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website_table_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_table_data_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website_table_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_table_data_id'))

    # ### end Alembic commands ###
